[package]
name = "radish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Framework
ggez = "0.9.0-rc0"
# UI
mooeye = {git = "https://github.com/Linus-Mussmaecher/mooeye"}
# ECS
legion = "^0.4"
# Serialization
serde = "^1.0"
toml = "^0.4"
serde_with = "^2.3"
# Random
rand = "^0.8"
# other
tinyvec = "^1.6"
[build-dependencies]
# Buidling
copy_to_output = "2.1.0"
glob = "0.3"