[package]
name = "radish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.0-rc0"
mooeye = { git = "https://github.com/Linus-Mussmaecher/mooeye" }
legion = "0.4.0"
copy_to_output = "2.1.0"